delete protocols static route 172.16.50.0/29
delete protocols static route 172.16.150.0/24

set firewall ipv4 name LAN-to-WAN default-action 'drop'
set firewall ipv4 name LAN-to-WAN default-log
set firewall ipv4 name LAN-to-WAN rule 1 action 'accept'

set firewall ipv4 name WAN-to-LAN default-action 'drop'
set firewall ipv4 name WAN-to-LAN default-log
set firewall ipv4 name WAN-to-LAN rule 1 action 'accept'
set firewall ipv4 name WAN-to-LAN rule 1 state 'established'
set firewall ipv4 name WAN-to-LAN rule 1 state 'related'

set firewall zone WAN from LAN firewall name 'LAN-to-WAN'
set firewall zone LAN from WAN firewall name 'WAN-to-LAN'

set service dns forwarding listen-address '172.16.50.2'
set service dns forwarding listen-address '172.16.150.2'
set service dns forwarding allow-from '172.16.50.0/29'
set service dns forwarding allow-from '172.16.150.0/24'
set service dns forwarding system
